logo: # add logo name
title: GreenMind - Um pouco da minha loucura
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "julio-cesar-ferreira-rodrigues.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: "GreenMind" # add banner title
banner-desc: "O caminho dessa loucura" # add banner description

# Author settings
author-pic: face.jpg # your photo
author-name: "GreenMind" # your name
about-author: "Olá eu sou o GreenMind , apaixonado e amante da tecnologia tenho como meta compartilhar o meu dia a dia e tentar ajudar pessoas que assim como eu também está iniciando nessa loucura." # about author
email: greenmind.sec@gmail.com # your email
phone: (14)-99701-0196 # your pnone number
website: https://greenmind.top # you website

# Social link
google_url:    # add url link
twitter_url:   # add url link 
instagram_url: # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url: "https://www.facebook.com/profile.php?id=100011756522947" # add url link

# Disqus
discus_identifier: mr-brown # add your discus identifier

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
