logo: # add logo name
title: "Coletivo URU - Arte, Ciência e Tecnologia.""
description: "Coletivo URU: arte, ciência e tecnologia, tem como objetivo, produzir, promover e investigar as artes mais precisamente tecnológicas e ou midiáticas para criar organismos híbridos entre atomos/bits."
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "urucoletivo.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: "Coletivo URU" # add banner title
banner-desc: "Coletivo URU - Arte, Ciência e Tecnologia." # add banner description

# Author settings
author-pic: face.jpg # your photo
author-name: "Coletivo URU" # your name
about-author: "" # about author
email: urucoletivo@gmail.com # your email
phone: (14)-xxxxx-xxxx # your pnone number
website: http://uru.art.br # you website

# Social link
google_url:    # add url link
twitter_url:   # add url link
instagram_url: # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url: "https://www.facebook.com/profile.php?id=100011756522947" # add url link

# Disqus
discus_identifier: mr-brown # add your discus identifier

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
